# Spring Security and OAuth 2.0
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 815675661448-2qg8ndd1a34bbbqu5smcmqgn4mtl1bo5.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          # 네이버에서는 스프링 시큐리티를 공식 지원하지 않기 때문에 common-OAuth2Provider에서 해주던 값들을 전부 수동으로 입력해야 함
          # Registration
          naver:
            client-id: GR1jKYAHnDWCLaCtgN8v
            client-secret: bBu4bfLs7B
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        # Provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

