spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    driverClassName: org.h2.Driver
    # Server Mode
    # url: jdbc:h2:tcp://localhost/~/GIT-REPO/aws-web-service/databases/webservice
    # Embedded Mode
    url: jdbc:h2:file:~/GIT-REPO/aws-web-service/databases/webservice
    # In-Memory Mode
    # url: jdbc:h2:mem:test
    username: sa
    password: